### ISSUE TITLE
Sfepy not reading supported mesh files

### ISSUE THREAD

**Issue by roshansuresh** [sfepy/sfepy#553]
Hi SfePy community, 

I am new to SfePy and am trying to analyse the displacements in a two bar truss. I created the truss model using FreeCAD and meshed it using Gmsh. I saved the mesh file in a variety of formats: .msh, .mesh (INRIA Medit), .inp (Abaqus input), .bdf (Nastran compatible), .med (Mesh Edit) and .vtk. Howver, when I try to call the mesh file through the problem description file and run it, it gives me the following error message:
raise ValueError('unsupported mesh file suffix! (%s)' % ext)
ValueError: unsupported mesh file suffix! (.vtk")
(For .vtk for instance).
Please advise. Any help is greatly appreciated.

P.S. : Issue #551 was reported by me. I'm mentioning this in case the problem causing that issue may be causing this issue. The SfePy installation was completed without faults. Of the optional dependencies I have not installed igakit, petsc4py, slepc4py, pymetis, scikits.umfpack and pysparse.

OS details: Windows 10

The problem description file is shown below:

r"""
Two-bar truss with two nodes pinned and the third node subjected to a constant force.

Find :math:`\ul{u}` such that:

.. math::
    \int_{\Omega} D_{ijkl}\ e_{ij}(\ul{v}) e_{kl}(\ul{u})
    = 0
    \;, \quad \forall \ul{v} \;,

where

.. math::
    D_{ijkl} = \mu (\delta_{ik} \delta_{jl}+\delta_{il} \delta_{jk}) +
    \lambda \ \delta_{ij} \delta_{kl}
    \;.
"""

from __future__ import absolute_import
from sfepy.mechanics.matcoefs import stiffness_from_youngpoisson
from sfepy.discrete.fem.utils import refine_mesh
from sfepy import data_dir

filename_mesh = data_dir + '/meshes/"two_bar_truss.vtk"'

refinement_level = 0
filename_mesh = refine_mesh(filename_mesh, refinement_level)

output_dir = '.' # set this to a valid directory you have write access to

young = 200000.0 # Young's modulus [MPa]
poisson = 0.27  # Poisson's ratio

options = {
    'output_dir' : output_dir,
}

regions = {
    'Omega' : 'all',
    'Bottom' : ('vertices in (y < 0.0001)', 'facet'),
    'Top' : ('vertices in (y > 86.5999)', 'facet'),
}

materials = {
    'Steel' : ({'D': stiffness_from_youngpoisson(2, young, poisson)},),
    'Load' : ({'.val' : [0.0, 100.0]},),
}

fields = {
    'displacement': ('real', 'vector', 'Omega', 1),
}

equations = {
   'balance_of_forces' :
   """dw_lin_elastic.2.Omega(Asphalt.D, v, u)
      = dw_point_load.0.Top(Load.val, v)""",
}

variables = {
    'u' : ('unknown field', 'displacement', 0),
    'v' : ('test field', 'displacement', 'u'),
}

ebcs = {
    'u1' : ('Top', {'u.1' : 0.0}),
    # 'YSym' : ('Left', {'u.0' : 0.0}),
}

solvers = {
    'ls' : ('ls.scipy_direct', {}),
    'newton' : ('nls.newton', {
        'i_max' : 1,
        'eps_a' : 1e-6,
    }),
}

**Comment by rc** [comment]
@roshansuresh Could you attach the mesh file, so that I can try loading it?

**Comment by roshansuresh** [comment]
Here's the various mesh files I tried to load:
[meshes.zip](https://github.com/sfepy/sfepy/files/3590817/meshes.zip)

**Comment by vlukes** [comment]
Hi @roshansuresh,

there are cells of dimensions 1, 2 and 3 in your meshes, that is the issue. There is a new commit, see  #554, which adds '3d' option to `script/convert_mesh.py`. So by running

`script/convert_mesh.py -3 mesh.vtk mesh_3d.vtk`

you remove 1D and 2D cells from your data.

VL

**Comment by rc** [comment]
@roshansuresh Note that sfepy cannot use meshes with elements of different topological dimensions. In 3D, all the cells need to be 3D, and of the same type (tetrahedron or hexahedron). The only exception is when using the shell term (`dw_shell10x`) - it requires 2D cells in 3D space.

Your `two_bar_truss.vtk` contains a bar that is surface only and a 3D bar. The PR #554 allows removing the surface-only bar. Is that what you wanted, or you wanted both bars with 3D elements? If you do need both, then sfepy is not the right tool to use.

**Comment by rc** [comment]
@roshansuresh I have just merged #544 by @vlukes, which closed this issue, but feel free to continue discussing here or reopening it.

**Comment by roshansuresh** [comment]
Thanks @vlukes and @rc for your help. Does the convert_mesh.py script work for other mesh file extensions as well?

**Comment by roshansuresh** [comment]
Also, when I try to convert my mesh.vtk file to mesh_3d.vtk, I get the following error message:

sfepy: reading mesh [line2, tri3, quad4, tetra4, hexa8] (two_bar_truss.vtk)...
sfepy: ...done in 0.02 s
sfepy: writing [line2, tri3, quad4, tetra4, hexa8] two_bar_truss_3d.vtk...
connectivity 1 -> 0 is not avaliable!
connectivity 1 -> 0 is not avaliable!
RuntimeError: ccore error (see above)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../script/convert_mesh.py", line 240, in <module>
    main()
  File "../script/convert_mesh.py", line 236, in main
    mesh.write(filename_out, io=io)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python37\lib\site-packages\sfepy-2019.2-py3.7-win-amd64.egg\sfepy\discrete\fem\mesh.py", line 430, in write
    io.write(filename, self, out, **kwargs)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python37\lib\site-packages\sfepy-2019.2-py3.7-win-amd64.egg\sfepy\discrete\fem\meshio.py", line 689, in write
    coors, ngroups, conns, mat_ids, descs = mesh._get_io_data()
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python37\lib\site-packages\sfepy-2019.2-py3.7-win-amd64.egg\sfepy\discrete\fem\mesh.py", line 389, in _get_io_data
    conn, cells = self.get_conn(desc, ret_cells=True)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python37\lib\site-packages\sfepy-2019.2-py3.7-win-amd64.egg\sfepy\discrete\fem\mesh.py", line 449, in get_conn
    conn = cmesh.get_incident(0, cells, cdim)
SystemError: <method 'get_incident' of 'sfepy.discrete.common.extmods.cmesh.CMesh' objects> returned a result with an error set
mem_free_mem(): error exit!
mem_free_mem(): error exit!

Is this just a system memory issue or is it something else?

**Comment by roshansuresh** [comment]
Update: I re-performed the installation instructions since I re-cloned the latest version of the github repository. After that I rechecked my model and found out that one of the portions of the model had been modelled as a surface and not a volume. After rectifying this and remeshing, I found 1D and 2D elements in my mesh. So, I tried to run the convert_mesh.py script again with the "-3" argument. However, I now get a new error:

sfepy: reading mesh [line2, tri3, quad4, tetra4, hexa8] (two_bar_truss_solid.vtk)...
sfepy: ...done in 0.02 s
Traceback (most recent call last):
  File "../script/convert_mesh.py", line 240, in <module>
    main()
  File "../script/convert_mesh.py", line 164, in main
    mesh = Mesh.from_data(mesh.name, *data)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python37\lib\site-packages\sfepy-2019.2-py3.7-win-amd64.egg\sfepy\discrete\fem\mesh.py", line 278, in from_data
    nodal_bcs=nodal_bcs)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python37\lib\site-packages\sfepy-2019.2-py3.7-win-amd64.egg\sfepy\discrete\fem\mesh.py", line 380, in _set_io_data
    ac(nm.concatenate(mat_ids)), descs)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

The new mesh file is attached herewith:
[two_bar_truss_solid.zip](https://github.com/sfepy/sfepy/files/3596813/two_bar_truss_solid.zip)

**Comment by vlukes** [comment]
OK, you probably need shell cells, i.e. 2D cells in 3D. @roshansuresh Am 
I right? For that case I updated the script by '--23d' or '-23' option. 
It selects 2D cells and remains 3D coordinates. See PR #556.

VL

**Comment by rc** [comment]
@roshansuresh the new mesh file seems to still have a 2D only part, see the attached screenshot (taken in paraview). 

![two_bar_truss_solid](https://user-images.githubusercontent.com/44282/64678117-3ceff180-d479-11e9-894d-e369d42bca37.png)
