### ISSUE TITLE
nodal_combination for boundary

### ISSUE THREAD

**Issue by Amirrgrbn** [sfepy/sfepy#795]
Hello, 
Since there was a problem in my previous issue #785, I want to use different approach with nodal combination, as in examples/linear_elastcity/nodal_lcbcs.py. 
I hope this works fine, as considering that I need the constrain in only on DOF of my boundary region (rigid works only in the case u.all and there are assertion problems).

Now, would you have a loook to attached code and let me know if there is a straight_forward way to solve it? Thanks

[facet_mesh.zip](https://github.com/sfepy/sfepy/files/8305278/facet_mesh.zip)

**Comment by rc** [comment]
Use (notice the comma after get_const to make it a tuple):
```
bc_left = LinearCombinationBC(name = 'bc_left', regions = [left , None], dofs = {'u.all' : None},
        dof_map_fun = None, kind = 'nodal_combination', arguments=(get_const,))
```

LCBCs and EBCs cannot be combined in a single node - you need to define the regions accordingly:
```
top = domain.create_region('top', 'vertices in (y > %.10f) -v r.left' % (max_y - eps), 'facet','Omega')
bottom = domain.create_region('bottom', 'vertices in (y < %.10f) -v r.left' % (min_y + eps), 'facet','Omega')
```
That should fix the assertion errors you mentioned also in the #785 version.

Also fix the name of bc_top:
```
bc_top = EssentialBC('bc_top', top, {'u.1' : bc_fun})
```

With the above changes, the code runs.

**Comment by Amirrgrbn** [comment]
thanks fort he answer, but there is still an issue. if I just reduce the top an bottom boundaries then the results will not be the same as I expect. Is there any way to use lcbcs in one dof? only u.0

**Comment by rc** [comment]
Give it a shot, I have tried modifying this [example](https://sfepy.org/doc/examples/linear_elasticity-nodal_lcbcs.html) where it seems to do something without errors.

With nodal_combination you can simulate the Dirichlet BCs (e.g. if you constrain all DOFs to a constant), so it might also be possible to have it behaving like there is u.1 given.

**Comment by Amirrgrbn** [comment]
I tried it, it works only having u.0, seems to follow the constrain but the values doesnt seem to be coorect. What I finally want is not like a Dirichlet but uniform displacement. ( to all nodes at left boundary follow the the top node in only x direction)

**Comment by Amirrgrbn** [comment]
Apart from this issue, there is another basic problem, that i dont get it. in the attache code and mesh, there should be ( if im not missing something) same displacement in x direction on both sides but the codes fails to give the correct result. one more thing, for such a simple and fully linear problem the residual of ls should be too small but here it is in order of 1e+5, which is a problem for sure. 
[Uploading mesh_simple.zip…]()

**Comment by Amirrgrbn** [comment]
Hello, Using the same code I have shared previously in git version of sfepy. gives the following error, but it works in conda version of sfepy. 

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_6464\298400560.py in <module>
     87 
     88 status = IndexedStruct()
---> 89 state = pb.solve(status=status)
     90 
     91 print('Nonlinear solver status:\n', nls_status)

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\problem.py in solve(self, state0, status, force_values, var_data, update_bcs, update_materials, save_results, step_hook, post_process_hook, post_process_hook_final, verbose)
   1427                 step_hook=step_hook, post_process_hook=post_process_hook)
   1428 
-> 1429             vec = tss(variables.get_state(self.active_only, force=False),
   1430                       init_fun=init_fun,
   1431                       prestep_fun=prestep_fun,

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\variables.py in get_state(self, reduced, follow_epbc, force)
    827     def get_state(self, reduced=False, follow_epbc=False, force=False):
    828         if reduced:
--> 829             vec = self.get_reduced_state(follow_epbc=follow_epbc, force=force)
    830 
    831         else:

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\variables.py in get_reduced_state(self, follow_epbc, force)
    775 
    776                 else:
--> 777                     raise ValueError('Reduced state DOFs are not available!')
    778 
    779             else:

ValueError: Reduced state DOFs are not available!

**Comment by Amirrgrbn** [comment]
Hello, 
I have an additional question, is it possible to have periodic boundary between vertex and facet? prbably not as I can see in the codes, but is there any way to implement it myself? or any suggestions?

**Comment by rc** [comment]
No, that is not possible. Any kinds of constraints can be potentially expressed using a penalty or the Lagrange multiplier approach, but I am not sure what the term should be in this case.

Did you resolve your previous issues mentioned above?

**Comment by Amirrgrbn** [comment]
Well, Im now using Periodic boundary Condition and using match_x, and seems to work (eventhough  have to take into account all vertices seperately). 
No, the code is not working on git version of sfepy; 
there is a further question, when I get the final stiffness matrix for a 6 node geometry in 2d nomally I expect 12DoFS, but the matrix is 17*17. further, using the field.get_dofs_in_region there is some extra dofs, that Im not sure what are they. 
I try to validate my results with analytical approach , but there are some differences in results and matrix dimentions.

**Comment by Amirrgrbn** [comment]
I got it, it was for approximation order

**Comment by rc** [comment]
Yes. For higher orders, the original nodes (vertex nodes) come first, then the additional ones: edge, face, bubble.

**Comment by Amirrgrbn** [comment]
Appreciate it, also thanks for the patience and helps, i think im ok for now.
